#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          omxremote
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the omxplayer daemon.
### END INIT INFO

NAME=omxremote
DAEMON=/usr/bin/$NAME
OPTIONS="/PATH/TO/MEDIA"
USER=pi
STOP_TIMEOUT=30
PIDFILE=/var/run/$NAME.pid

export PATH="${PATH:+$PATH:}/sbin"

[ -x $DAEMON ] || exit 0

[ -e /etc/default/$NAME ] && . /etc/default/$NAME

. /lib/lsb/init-functions

start_daemon () {
    start-stop-daemon --start \
                      --background \
                      --chuid $USER \
                      --pidfile $PIDFILE \
                      --make-pidfile \
                      $START_STOP_OPTIONS \
                      --exec $DAEMON -- $OPTIONS || log_end_msg $?
    log_end_msg 0
}

case "$1" in
    start)
        log_daemon_msg "Starting omxremote daemon" "$NAME"
        start_daemon
        ;;
    stop)
        log_daemon_msg "Stopping omxremote daemon" "$NAME"
        start-stop-daemon --stop --quiet \
            --exec $DAEMON --retry $STOP_TIMEOUT \
            --oknodo || log_end_msg $?
        log_end_msg 0
        ;;
    reload)
        log_daemon_msg "Reloading omxremote daemon" "$NAME"
        start-stop-daemon --stop --quiet \
            --exec $DAEMON \
            --oknodo --signal 1 || log_end_msg $?
        log_end_msg 0
        ;;
    restart|force-reload)
        log_daemon_msg "Restarting omxremote daemon" "$NAME"
        start-stop-daemon --stop --quiet \
            --exec $DAEMON --retry $STOP_TIMEOUT \
            --oknodo || log_end_msg $?
        start_daemon
        ;;
    status)
        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
    *)
        log_action_msg "Usage: /etc/init.d/$NAME {start|stop|reload|force-reload|restart|status}" || true
        exit 2
        ;;
esac

exit 0
